// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store_Management.Data;

#nullable disable

namespace Store_Management.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240719114532_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store_Management.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Popular contemporary novelist and screenwriter.",
                            IsActive = false,
                            Name = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acclaimed poet and author of modern Vietnamese literature.",
                            IsActive = false,
                            Name = "Nguyễn Hồng"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Novelist known for exploring social issues in Vietnam.",
                            IsActive = false,
                            Name = "Nguyễn Thành Long"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Award-winning author of novels and poetry, focusing on Vietnamese history and culture.",
                            IsActive = false,
                            Name = "Nguyễn Phan Quế Mai"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Young novelist and short story writer known for contemporary themes.",
                            IsActive = false,
                            Name = "Lê Minh Khuê"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern poet and essayist exploring existential and philosophical themes.",
                            IsActive = false,
                            Name = "Bùi Anh Tấn"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contemporary writer of short stories and novels reflecting on urban life.",
                            IsActive = false,
                            Name = "Phan Hồn Nhân"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Novelist and playwright known for feminist themes in Vietnamese literature.",
                            IsActive = false,
                            Name = "Trịnh Bích Ngân"
                        });
                });

            modelBuilder.Entity("Store_Management.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPage")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookSize = "15.9 x 1.3 x 22.2",
                            CategoryId = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2047),
                            Description = "Classic novel by F. Scott Fitzgerald",
                            ISBN = "BK235",
                            ImageUrl = "the_great_gatsby.jpg",
                            IsActive = true,
                            Name = "The Great Gatsby",
                            NumberOfPage = 30,
                            Price = 150000m,
                            PublicationYear = 2025,
                            PublisherId = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            BookSize = "16.0 x 2.0 x 23.0",
                            CategoryId = 9,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2050),
                            Description = "Comprehensive guide to best practices in Java programming.",
                            ISBN = "BK236",
                            ImageUrl = "effective_java.jpg",
                            IsActive = true,
                            Name = "Effective Java",
                            NumberOfPage = 400,
                            Price = 450000m,
                            PublicationYear = 2024,
                            PublisherId = 2,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            BookSize = "18.0 x 3.0 x 24.0",
                            CategoryId = 10,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2053),
                            Description = "Deep dive into C# programming with professional tips and tricks.",
                            ISBN = "BK237",
                            ImageUrl = "pro_csharp_8.jpg",
                            IsActive = true,
                            Name = "Pro C# 8.0",
                            NumberOfPage = 1200,
                            Price = 550000m,
                            PublicationYear = 2023,
                            PublisherId = 1,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            BookSize = "14.0 x 2.5 x 21.0",
                            CategoryId = 12,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2055),
                            Description = "Epic science fiction novel by Frank Herbert.",
                            ISBN = "BK238",
                            ImageUrl = "dune.jpg",
                            IsActive = true,
                            Name = "Dune",
                            NumberOfPage = 900,
                            Price = 60000m,
                            PublicationYear = 2021,
                            PublisherId = 2,
                            Stock = 200
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            BookSize = "15.0 x 3.5 x 23.0",
                            CategoryId = 14,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2057),
                            Description = "All the classic tales of Sherlock Holmes by Arthur Conan Doyle.",
                            ISBN = "BK239",
                            ImageUrl = "sherlock_holmes.jpg",
                            IsActive = true,
                            Name = "Sherlock Holmes: The Complete Novels and Stories",
                            NumberOfPage = 2200,
                            Price = 980000m,
                            PublicationYear = 2022,
                            PublisherId = 4,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            BookSize = "16.0 x 2.0 x 24.0",
                            CategoryId = 15,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2059),
                            Description = "Michelle Obama's deeply personal memoir.",
                            ISBN = "BK240",
                            ImageUrl = "becoming.jpg",
                            IsActive = true,
                            Name = "Becoming",
                            NumberOfPage = 400,
                            Price = 500000m,
                            PublicationYear = 2020,
                            PublisherId = 4,
                            Stock = 120
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            BookSize = "17.0 x 2.5 x 25.0",
                            CategoryId = 16,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2061),
                            Description = "Comprehensive history of World War II by Antony Beevor.",
                            ISBN = "BK241",
                            ImageUrl = "the_second_world_war.jpg",
                            IsActive = true,
                            Name = "The Second World War",
                            NumberOfPage = 800,
                            Price = 2000000m,
                            PublicationYear = 2019,
                            PublisherId = 4,
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            BookSize = "20.0 x 3.0 x 28.0",
                            CategoryId = 17,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(2063),
                            Description = "A comprehensive introduction to art and artists from around the world.",
                            ISBN = "BK242",
                            ImageUrl = "the_art_book.jpg",
                            IsActive = true,
                            Name = "The Art Book",
                            NumberOfPage = 600,
                            Price = 85000m,
                            PublicationYear = 2018,
                            PublisherId = 4,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("Store_Management.Data.Models.BookSerialNumber", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("BookSerialNumber");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "English Book"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Java",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "C#",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Python",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Space Opera",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "High Fantasy",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Detective",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Autobiography",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "World War II",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Painting",
                            ParentId = 8
                        });
                });

            modelBuilder.Entity("Store_Management.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CitizenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi, Viet Nam",
                            Age = 30,
                            CitizenId = "0049393859",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1948),
                            Email = "admin@gmail.com",
                            FullName = "Le Trung Ha",
                            IsActive = true,
                            Password = "AQAAAAEAACcQAAAAELkmiywABvS7CuDMOizvFZAcM0PFm41LpVWfrviktituMRaltQuJab+Nvm4fu84AKQ==",
                            PhoneNumber = "094859404",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ha Noi, Viet Nam",
                            Age = 30,
                            CitizenId = "0049393859",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1958),
                            Email = "c@gmail.com",
                            FullName = "Tran Van B",
                            IsActive = true,
                            Password = "AQAAAAEAACcQAAAAELkmiywABvS7CuDMOizvFZAcM0PFm41LpVWfrviktituMRaltQuJab+Nvm4fu84AKQ==",
                            PhoneNumber = "094859404",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ha Noi, Viet Nam",
                            Age = 30,
                            CitizenId = "0049393859",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1961),
                            Email = "b@gmail.com",
                            FullName = "Nguyen Van A",
                            IsActive = true,
                            Password = "AQAAAAEAACcQAAAAELkmiywABvS7CuDMOizvFZAcM0PFm41LpVWfrviktituMRaltQuJab+Nvm4fu84AKQ==",
                            PhoneNumber = "094859404",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ha Noi, Viet Nam",
                            Age = 30,
                            CitizenId = "0049393859",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1963),
                            Email = "a@gmail.com",
                            FullName = "Nguyen Thi C",
                            IsActive = false,
                            Password = "AQAAAAEAACcQAAAAELkmiywABvS7CuDMOizvFZAcM0PFm41LpVWfrviktituMRaltQuJab+Nvm4fu84AKQ==",
                            PhoneNumber = "094859404",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Store_Management.Data.Models.EmployeePaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeePaymentRecord");
                });

            modelBuilder.Entity("Store_Management.Data.Models.KPIRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("KPIRecords");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1983),
                            IsActive = false,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1984),
                            IsActive = false,
                            Name = "NXB Giáo Dục"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1985),
                            IsActive = false,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1986),
                            IsActive = false,
                            Name = "NXB Hội Nhà Văn"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 18, 45, 32, 1, DateTimeKind.Local).AddTicks(1987),
                            IsActive = false,
                            Name = "NXB Văn Học"
                        });
                });

            modelBuilder.Entity("Store_Management.Data.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Store_Management.Data.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItem");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Book", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store_Management.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store_Management.Data.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Store_Management.Data.Models.BookSerialNumber", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Category", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Store_Management.Data.Models.KPIRecord", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Sale", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Store_Management.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Store_Management.Data.Models.SaleItem", b =>
                {
                    b.HasOne("Store_Management.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store_Management.Data.Models.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Store_Management.Data.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
